---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
  bookdown::html_document2: default
  bookdown::word_document2: default
documentclass: book
bibliography: references.bib
always_allow_html: true
header-includes:
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
- \usepackage[default]{sourcesanspro}
- \usepackage[T1]{fontenc}
- \usepackage{amsmath}
- \usepackage{dcolumn}
- \usepackage{url}
---

```{block type='savequote', include=knitr::opts_knit$get('rmarkdown.pandoc.to') == 'latex', quote_author='(ref:goethe-quote)'}
He who chases two rabbits catches neither.

<!-- ending a line with a lonely backslash inserts a linebreak -->
```
(ref:goethe-quote) --- Confucius [@caseau2020impact]

# Conclusion and Policy Derivatives

This study examined the potential impacts of the transformation of MFIs in Africa. The conversion of MFIs has seen a substantial number of MFIs that previously operated as NGOs convert to a commercial, profit-seeking model that relies less on donations and state subsidies and more on funding from capital markets. Most of the concerns in the literature have been on the potential of mission drift among the transformed MFIs [@armendariz2011mission; @serrano2014microfinance]. Mission drift occurs when MFIs stresses financial sustainability at the expense of the social goal of offering appropriate and affordable financial services to the financially excluded [@d2017ngos]. So far, there is lack of consensus on the extent and direction of the effect of transformation of MFIs. Much of the extant research draws from global datasets, which could mask regional heterogeneity. 

The research examined the factors that drive the conversion of MFIs to the commercial model. This research research oversight is surprising given that as more MFIs adopt the profit-oriented model, an appropriate policy framework should be in place to support the transformation and address potential side effects of the conversion. The research then explored the extent to which the conversion of MFIs to the commercial model affects financial inclusion in Africa. Critically, the study also examined the levels of financial and social efficiency of MFIs and the factors that determine whether or not an MFI meets financial and social goals. In this regard, much of the literature examines the financial and social outcomes of MFIs separately instead of evaluating them jointly as two sides of the same coin. Also, few researchers examine the financing model of MFIs, considering that, as hybrid organisations, the mainstream capital structure theory may be deficient as it addresses the financing of commercial firms. 

Specifically, the study sought answers to the following questions in light of the research gaps highlighted. 

1. Why do some MFIs in Africa transform into the commercial model while others retain the NGO Model?
2. To what extent has the institutional transformation of MFIs in Africa affected financial inclusion?
3. After transformation, what factors explain the joint level of sustainability and outreach by MFIs in Africa?
4. What are the drivers of financial efficiency, social efficiency and socio-financial efficiency of MFIs in Africa?
5. What are the factors that influence the choice of financing sources by transformed MFIs in Africa? 

## Highlight of the Results

The first research question examines factors that make MFIs to adopt the commercial, profit-seeking model that gets funding from capital markets instead of reliance on donations and subsidies. The analysis show that at the firm level, age and size influence transformation. Legal tradition, institutional quality, and stock market development are significant factors at the country level. Specifically, larger and older MFIs are less likely to be NGOs. These results suggest that as MFIs mature, they tend to convert to the commercial model either due to pressure from donors or the decision by management to pursue the double bottom line as they get more financially sustainable and as donor support subsides. MFIs in civil law countries are also less likely to be NGOs, while those in countries that follow other legal traditions are more likely to adopt the commercial model. 

Again,  Institutional quality raises the chances of MFI conversion to the commercial model. Institutional quality captures a wide range of governance measures that enhance contract enforcement and property rights. Hence, countries with stronger institutions tend to attract more private investments and hence the higher rate at which MFIs adopt the commercial model. Stock market capitalisation and private credit to GDP have a negative relationship with transformation. The development of capital markets corresponds to better access to financial services, a pre-condition for financial inclusion. Hence, MFIs in countries with well-developed financial markets will likely be competing against established financial intermediaries for the existing market. The competition limits the financial viability of MFIs. Hence, MFIs in these markets will likely remain NGOs that serve small population in the fringes of the market. 

I then examined how the transformation of MFIs in Africa has affected or could potentially affect financial inclusion on the continent. The results show that the change from the NGO model to the commercial models could negatively affect the depth of financial outreach, especially given that NGOs characteristically have better outreach to women and advance smaller denomination loans on average than for-profit MFIs. Also, NGOs have higher median gross loans to assets ratio than other legal forms of MFIs except for credit unions/cooperatives. Overall, the results indicate the potential mission drift, where MFIs that convert to the for-profit model focus more on financial sustainability to the detriment of outreach to the unbanked. 

in Chapter 4, I examined the levels and drivers of financial and social efficiency of MFIs in Africa. In this case, i captured the efficiencies using output oriented data envelopment analysis (DEA). Broadly, our results show a trend of declining financial efficiency by MFIs but no discernible trend in social and socio-financial efficiency. However, NGOs have markedly better social efficiency and socio-financial efficiency scores than other legal forms of MFIs. Surprisingly, only cooperatives and rural banks consistently outperform NGOs financially. The proxies for financial sector development, stock market capitalization to GDP and private credit to GDP,  have a negative relationship with social and socio-financial efficiency. Financial efficiency has an inverse relationship with both the size and asset structure of MFIs. These results suggest that the commercialization of MFIs does not necessarily improve their financial sustainability.

Related to chapter 4, chapter 5 examined the extent to which MFIs in Africa achieve financial and social goals. The chapter also sought to uncover factors that drive the achievement of the dual objectives. The results show that most MFIs in Africa attain the dual objectives, at 35.88% compared to 14.76% that fail in both missions. 23.85% fail socially but succeed financially, and 25.55% succeed socially while failing financially. In total, 61.43% of MFIs attain their social goals. 40.31% fail financially. However, these results vary across the legal status of an MFI. Rural banks and NGOs are more likely to achieve the dual goals than banks, NBFIs and credit unions. Accordingly, the legal status of an MFI is the most significant driver of the extent of the achievement of the dual goals. NGOs have the highest likelihood of achieving both financial and social goals. This result highlights the risk of mission drift should MFIs convert to the for-profit model. Larger MFIs have a higher chance of meeting financial and social goals. Likewise, larger firms are more likely to succeed socially while failing financially, meaning that larger firms emphasise social impact. Age raises the probability that an MFI will fail financially and socially, as does stock market capitalisation to GDP that proxies capital markets development. Lastly, MFIs in countries following civil law and other legal traditions are more likely to meet at least one of the objectives, unlike MFIs in common law countries. 

Finally, in chapter 6, I looked into the factors that drive the adoption of alternative finance sources. In this case I examined four primary sources of finance; leverage, equity, deposits, and donations. The significant determinants of financing at the firm level are size, age, legal status, and profitability consistent with theory. For example, asset structure varies inversely with leverage. At the country level, institutional quality (KKM) varies inversely with deposits and donations. Interestingly, coefficients of financial development are not significant across all financial structure proxies, going against stylised facts on the macro-level drivers of firms’ financing structure. The results suggest that firm-level factors are more relevant in determining the financing structure of MFIs. 

## Policy Implications 

There are some important policy derivatives from the outcomes of the research. But first, it is important to restate the objectives and outcomes of the research that form the basis of the policy recommendations. The study sought to examine the possible impacts of the transformation of MFIs in Africa on financial inclusion. The transformation aimed at making MFIs less reliant on donor funding and state subsidies by making them financially sustainable. Financially sustainable MFIs would then experience mission expansion instead of mission drift [@mersland2010microfinance]. This logic arose after the cold war and the rise of neo-liberalism that emphasises the financial viability of institutions. I first look at the implications of the research on the financial and social goals of MFIs in Africa, and the implications on financial inclusion.

First, the conversion of MFIs does not appear to improve the financial sustainability of MFIs in Africa. The conversion of MFIs does not help improve their financial sustainability, at least in the short and medium term. Overall, MFIs fare badly financially. However, NGOs have better financial efficiency scores than banks and NBFIs. Only cooperatives and rural banks do better financially than NGOs. With cooperatives more inclined to serving their members more than offering financial services to the unbanked, it appears that the argument for financial sustainability as an enabler of mission expansion does not hold.  

Indeed, the analysis shows that NGOs form the largest proportion of MFIs that are financially viable while maintaining their social focus. This result shows that NGOs are better at balancing social and financial goals more than the converted MFIs. Even where they fail financially, NGOs have the highest proportion of MFIs that succeed socially, meaning that NGOs are more keen on their social mission than on financial goals. The mission of NGOs together with donor support could be the reason they are able to stick to their social mission [@berbegal2019impact].The results show that there is high likelihood of mission drift where MFIs that seek financial sustainability focus less of availing financial services to the financially excluded. These results are an indiction against the coercive pressure from donors and governments for MFIs to be financially viable. 

These results leave two possible policy interventions. First, are there policies that would support the conversion of MFIs from NGOs to the commercial model without causing mission drift? Secondly, among the converted MFIs what kind of support would best allow them to be financially sustainable without losing focus on their social goals? Third, what financing options are best suited to support the dual objectives of microfinance institutions? Fourth, there is a prominent proposition by @morduch1999microfinance and @morduch2000microfinance that advocates for allowing a broad range of MFIs- from those that seek financial sustainability to those that focus on financial exclusion with donor and state support. I examine these points next. 

Chapter 2 established some of the factors that drive the conversion of MFIs to the commercial model. I found that age and size influence the transformation, whereas legal tradition, institutional quality, and stock market development are significant factors at the country level. Larger MFIs and MFIs located in countries with “other” legal traditions are more likely to follow the commercial model. Institutional quality raises the chances of conversion, while stock market capitalisation has a negative relationship with transformation. Among the factors associated with a higher chance that an MFI will achieve both financial goals and social goals are MFI age, size and legal status, country legal tradition, level of capital markets development, and institutional quality. The latter three have a negative relationship with the extent of achieving financial and social goals. 

These results imply that MFIs located in countries with better institutions and by extension better capital markets development are better following the commercial model especially given the low levels of financial exclusion in these countries. Better institutions allow MFIs in these countries to achieve their financial goals even when not meeting their social goals without extensive loss in public welfare. On the contrary, MFIs located in countries with low levels of financial development with low institutional quality would better retain a greater degree of NGO-type MFIs. The substantial levels of financial exclusion in these countries mean that conversion of MFIs will have substantial impact on financial inclusion which goes against the millennium development goals and the African Union Agenda 2063 on financial inclusion for all. It means that for the achievement of financial inclusion goals, some level of donations and state subsidies are necessary especially in countries with large financial inclusion gaps.The neo-liberal approach to the coercive adoption of the commercial mode of MFIs uniformly across all countries, especially in Africa, is inappropriate as @bateman2010doesn notes. 

Also, @morduch1999microfinance and @morduch2000microfinance argue that the microfinance industry should allow for a wide range of MFIs. In this model, the NGO-type MFIs could still rely on donations and subsidies and reach out to the poorest section of the population that is shunned by the mainstream financial system. Then, as these customers get better off, they could join the mainstream financial system. This models implies that the customers of MFIs could be segmented and served on the basis of need. This model will then allow for the coexistence of different types of MFIs- profit seeking versus NGO type - instead of prioritizing some types of MFIs over others. To extend this argument, the model of microfinance should also be different depending on the differing situations between countries. As noted, countries with very low levels of financial inclusion due follow levels of capital markets development should allow and support more NGO-type MFIs, relative to countries with relatively lower levels of financial exclusion. 

A related issue in financing hybrid organisations like MFIs is the rise of impact finance and blended finance. Impact investing relates to the use of corporate principles to generate environmental, social and governance (ESG) gains over and above financial goals. The defining features of impact investing are as follows. 

- Intentionality of impact,

- Expectation of financial returns, and

- Measurable impact along non-financial dimensions—notably, social, environmental, or governance (or two or three of these) dimensions [@caseau2020impact]. 

This research has established the decline in donations to MFIs in line with the rise of neo-liberalism. Also, most MFIs have poor financial results and may not attract capital market funding.Impact financing could bridge this deficiency by offering support without expecting financial returns as high as those demanded by mainstream providers of capital. @barber2021impact show that impact investors derive non-pecuniary utility from investing in dual-objective Venture Capital (VC) funds, thus sacrificing returns. The entry of impact financing into microfinance could help mitigate the administrative challenges associated with the double bottom-line objective of MFIs. 

A related concept is blended finance [@attridge2019blended]  which the [IFC](https://www.ifc.org/wps/wcm/connect/topics_ext_content/ifc_external_corporate_site/bf) defines as follows:

>The use of relatively small amounts of concessional donor funds to mitigate specific investment risks and help rebalance risk-reward profiles of pioneering investments that are unable to proceed on strictly commercial terms. Concessional funds are structured as co-investments, with an expectation of reflows for future investments or other uses ^[This definition is available https://www.ifc.org/wps/wcm/connect/topics_ext_content/ifc_external_corporate_site/bf].

Blended finance would be especially useful for MFIs in the initial stages of conversion when financial goals may be hard to attain. Then, as MFIs adjust to the commercial model and become more financially sustainable, the blended funding could scale down. 

The providers of impact and blended financing should consider the needs of MFIs in each country or region. For instance, this research has established that MFIs in countries with high levels of financial development do not fare well financially. Still, there is a substantial number of marginalised people that would benefit from the services of MFIs. MFIs in countries with low levels of financial development have better financial prospects as they serve a relatively large pool of clients. In this case, impact and blended finance could complement financing from the mainstream financial markets. 

## Possible Future Research Directions

The research explores some possible areas for future research. In this section, I describe some potential areas for future research. First, it would be interesting to examine MFIs that succeed financially as well as socially after conversion and see what differentiates them. The research could then examine firm level factors that drive the extent that MFIs achieve financial and social goals. These firm-level drivers may include, for example, inefficient employment of resources like human capital which could be addressed by increased use of Fintech or optimising the number of clients per loan officer. This examination would help inform management of MFIs as well as policy makers on the possible areas of intervention to allow MFIs to meet the double bottom line objective. 

Along the same line, it would be worthy examining the longer term examination of financial sustainability vis-a-vis social performance measures of MFIs. This current research did not have the benefit of a long time series to allow the tracking of financial and social goals of MFIs. It is possible that MFIs may struggle financially at the initial stages but improve as they adjust to the commercial model of operations. This kind of research would help uncover areas that transforming MFIs should address in order to swiftly adjust and be able to meet financial and social goals. 

Even as MFIs convert to the commercial model, a new reality has hit the financial services industry: the rise of Fintech. FinTech promises to deliver financial services at a lower cost than the traditional brick and mortar model. In this regard, MFIs that are converting to the commercial model could benefit immensely from adopting FinTech, both from the financial sustainability and the social outreach perspectives. From this perspective, it would be critical to assess the extent that MFIs that transform invest in FinTech and how the investment in FinTech by MFIs impacts their investments in physical infrastructure, profitability and outreach. 

Perhaps the most critical issue for future research is establishing the best ways to finance MFIs that transform to the commercial model. Much of the literature examines the financing structures of financial intermediaries that only have a commercial goal. Thus, the capital structure theory do not address MFIs that have dual goals. In the mainstream capital structure theory, a firm's value will increase with increased debt upto that time where the costs of financial distress outweigh the corporate and personal tax advantage of debt. In the case of MFIs, the value of a firm is not just the value of debt and equity but also the intangible value arising out of meeting social goals that raises the worth of the firm to stakeholders. Hence, it is paramount to establish the best financing structure to optimise the hybrid goals of MFIs. 





