`r if(knitr:::is_latex_output()) '\\startappendices'`

`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'` 

<!-- If you feel it necessary to include an appendix, it goes here. The first appendix should include the commands above. -->


# The First Appendix

In my data analysis, I have relied a great deal on the efforts of the work by the `R foundation` [@R], `R Studio`, and many other contributors to the R project. The listing below shows the packages utilised in my research. 

:::::::::::::: {.columns}
::: {.column width="40%"}

bookdown[@bookdown],
broom[@broom],
caret[@caret],
car[@car],
corrplot[@corrplot2021],
GGally[@ggally],
ggalt[@ggalt],
ggeasy[@ggeasy],
gghalves[@gghalves],
ggrepel[@ggrepel],
ggthemes[@ggthemes],
gmnl[@gmnl],
gmodels[@gmodels],
gplots[@gplots], 
gridExtra[@gridextra],
gtable[@gtable],
here[@here],
janitor[@janitor],
kableExtra[@kableExtra],
knitr[@knitr], 
lme4[@lme4], 
lmtest[@lmtest].

:::
::: {.column width="40%"}

margins[@margins],
mice[@mice],
nnet[@nnet],
oxforddown[@lyngsOxforddown2019],
pacman[@pacman], 
patchwork[@patchwork], 
pcse[@pcse],
pglm[@pglm], 
plm [@plm],
prettydoc[@prettydoc], 
pROC[@pROC], 
psych[@psych], 
Rchoice[@rchoice], 
rDEA[@rdea],
readxl[@readxl],
rmarkdown[@rmarkdown],
skimr[@skimr],
stargazer[@stargazer],
thesisdown[@thesisdown2021],
tidymodels[@tidymodels],
tidyverse[@tidymodels],
treemapify[@treemap], 
viridis[@viridis], 
wesanderson[@wesanderson],
zoo[@zoo].

:::
::::::::::::::







# The Second Appendix, for Fun
