---
output:
  pdf_document: default
  html_document: default
---
This dissertation explores the impacts of Microfinance Institutions’ (MFIs) transformation from Non-Governmental Organizations (NGOs) model to profit-seeking commercial firms’ model. Specifically, the research examines the drivers of this MFI operating model transformation and the transformation’s attendant effects on financial inclusion in Africa. The study also explores the drivers of financial efficiency, social efficiency and joint socio-financial efficiency of Africa’s MFIs. Lastly, the study examines the prevailing financing structures of Africa’s MFIs and the factors associated with these MFIs’ choice of financing alternatives.

Fundamentally, older MFIs and MFIs in civil law countries are more likely to convert their operational mode from the conventional NGO model to the for-profit, financially sustainable model. Additionally, larger MFIs and MFIs located in countries with “other” legal traditions and better institutional quality, are more likely to transform. However, stock market size negatively relates to the odds of transformation. Interestingly, the transformation to the for-profit model negatively affects the depth of MFIs’ outreach. MFIs with NGO-based models reach more women and advance smaller denomination loans. Similarly, NGO-type MFIs have markedly better social efficiency and socio-financial efficiency scores than other MFIs models. Only cooperatives and rural banks consistently outperform traditional NGO-type MFIs in financial efficiency. Stock market and private credit market sizes, proxies for financial sector development, negatively affect social and socio-financial efficiencies.

Most MFIs in Africa attain both financial and social goals. However, rural banks and NGO-type MFIs are more likely to achieve the dual goals than other MFI legal forms. Age, size, financial development, institutional quality, legal tradition, and legal status are statistically significant factors in MFIs attaining joint financial and social objectives. Furthermore, at the firm level, size, age, legal status, and profitability drive MFIs’ choice of financing alternatives. For example, asset structure varies inversely with leverage. And at the country level, institutional quality varies inversely with deposits and donations, respectively. Overall, most of these results indicate that the transformation of MFIs in Africa, does not necessarily lead to financial sustainability; instead, it appears to be harmful to the financial inclusion goal. There also seems to exist a need to craft better financing models for MFIs to support their twin objectives of social outreach and sustainability.